### ISSUE TITLE
New docker image causes errors

### ISSUE THREAD

**Issue by gabrielBarbutti** [eubr-bigsea/limonero#48]
The following erros happened after I enterred the datasources page in my browser
```
limonero_1    | 2018-08-22 20:49:28,658 limonero.app WARNING  Hadoop JARs not found. Data source upload will not work. Set HADOOP_HOME and/or SPARK_HOME environment variables to the correct path.                                                                             
limonero_1    | (17) wsgi starting up on http://0.0.0.0:23402
limonero_1    | (17) accepted ('172.21.0.5', 40376)
limonero_1    | 2018-08-22 20:49:35,008 limonero.data_source_api ERROR    Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with DataSourcePermission.permission has an attribute 'ingettext'                                                           
limonero_1    | Traceback (most recent call last):
limonero_1    |   File "/usr/local/limonero/limonero/data_source_api.py", line 103, in get
limonero_1    |     data_sources, PermissionType.values())
limonero_1    |   File "/usr/local/limonero/limonero/data_source_api.py", line 61, in _filter_by_permissions
limonero_1    |     DataSourcePermission.permission.ingettext(permissions)
limonero_1    |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 198, in __getattr__
limonero_1    |     key)
limonero_1    | AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with DataSourcePermission.permission has an attribute 'ingettext'                                                                                                     
limonero_1    | 172.21.0.5 - - [22/Aug/2018 20:49:35] "GET /datasources?asc=false&enabled=true&page=1&size=7&sort=updated&user_id=1 HTTP/1.0" 500 227 0.037937
```

**Comment by gabrielBarbutti** [comment]
limonero/py4j_init.py file references SPARK_HOME even after that was removed from the Dockerfile
